version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=user
      - POSTGRESQL_DATABASE=AuthentificationDB
    ports:
      - '5432:5432'
    volumes:
      - ./Authentification/data/initdb/:/docker-entrypoint-initdb.d
      - ./Authentification/data/initdb/:/bitnami/postgresql
  authentification:
    build:
      context: ./Authentification
    ports:
      - '5000:5000'
    env_file:
      - ./Authentification/.env.prod
  front:
    build:
      context: ./front
    ports:
      - '5001:3000'
  profil:
    build:
      context: ./profil
    ports:
      - '5006:5006'
    env_file:
      - ./Profil/.env.prod
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./Profil/docker/initdb/:/docker-entrypoint-initdb.d/
      - ./Profil/docker/data/db/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: ProfilDB
    ports:
      - "27017:27017"
