version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=user
      - POSTGRESQL_DATABASE=AuthentificationDB
    ports:
      - '5432:5432'
    volumes:
      - ./Authentification/data/initdb/:/docker-entrypoint-initdb.d
  authentification:
    build:
      context: ./Authentification
    ports:
      - '5000:5000'
    env_file:
      - ./Authentification/.env.prod
  front:
    build:
      context: ./front
    ports:
      - '3000:3000'
    env_file:
      - ./Front/.env.prod
  profil:
    build:
      context: ./profil
    ports:
      - '5006:5006'
    env_file:
      - ./Profil/.env.prod
  games:
    build:
      context: ./games
    ports:
      - '5009:5009'
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./Profil/docker/initdb/:/docker-entrypoint-initdb.d/
      - ./Profil/docker/data/db/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: ProfilDB
    ports:
      - "27017:27017"
  faces:
      build:
        context: ./faces
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./faces:/code
      ports:
        - "8000:8000"